import Head from "next/head";
import Image from "next/image";
import Header from "../components/container/Header";
import Section from "../components/container/Section";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Header />
      </Section>
    </>
  );
}
