export default function Content() {
  return (
    <div className="w-full bg-red-800 relative">
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>hallo</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
      <h1>okk</h1>
    </div>
  );
}
